"""
Base interface for Embedding Providers.
"""

from abc import ABC, abstractmethod


class EmbeddingProvider(ABC):
    """
    Abstract Base Class for generating vector embeddings from text.
    """

    @abstractmethod
    def generate_embedding(self, text: str) -> list[float]:
        """
        Generate a single vector embedding for the input text.

        :param text: Cleaned text block to embed.
        :returns: List of floats representing the embedding vector.
        """
        pass

    @abstractmethod
    def generate_batch_embeddings(self, texts: list[str]) -> list[list[float]]:
        """
        Generate batch vector embeddings for the list of input texts.

        :param texts: List of cleaned text blocks.
        :returns: List of lists of floats representing embedding vectors.
        """
        pass

    @abstractmethod
    def embedding_dimension(self) -> int:
        """
        Return the dimensions of the vector generated by this provider's model.
        """
        pass

    @abstractmethod
    def model_name(self) -> str:
        """
        Return the name of the underlying model.
        """
        pass

    @abstractmethod
    def health_check(self) -> bool:
        """
        Perform health check on the embedding model/backend.
        """
        pass
