"""Schemas package."""

from app.schemas.auth import RefreshTokenRequest, TokenResponse, UserLogin
from app.schemas.curriculum import (
    BloomLevelCreate,
    BloomLevelRead,
    CourseCreate,
    CourseOutcomeCreate,
    CourseOutcomeRead,
    CourseOutcomeUpdate,
    CourseRead,
    CourseUpdate,
    DepartmentCreate,
    DepartmentRead,
    DepartmentUpdate,
    ImportReportItem,
    KnowledgeLevelCreate,
    KnowledgeLevelRead,
    ProgramCreate,
    ProgramRead,
    ProgramUpdate,
    SemesterCreate,
    SemesterRead,
    SemesterUpdate,
    TopicCreate,
    TopicMappingCreate,
    TopicMappingRead,
    TopicMappingUpdate,
    TopicRead,
    TopicUpdate,
    UnitCreate,
    UnitRead,
    UnitUpdate,
)
from app.schemas.document_processing import (
    DocumentMetadataRead,
    DocumentProcessingRead,
    DocumentTextRead,
)
from app.schemas.chunk import (
    ChunkRead,
    ChunkMappingRead,
    ChunkDetailsRead,
    ChunkPreviewItem,
    ChunkStatistics,
    ChunkQualityReportItem,
    DocumentChunkingJobRead,
)
from app.schemas.resource import ResourceRead, ResourceUpdate
from app.schemas.response import APIResponse, PaginatedResponse
from app.schemas.user import UserCreate, UserRead, UserUpdate
from app.schemas.retriever import (
    MetadataFilterModel,
    RetrieveRequest,
    RetrieveTopKRequest,
    RetrieveCourseRequest,
    RetrieveTopicRequest,
    RetrieveUnitRequest,
    ContextChunkRead,
    ContextPackageRead,
)
from app.schemas.prompt import (
    PromptTemplateCreate,
    PromptTemplateUpdate,
    PromptTemplateRead,
    PromptBuildRequest,
    PromptBuildResponse,
    PromptValidationRequest,
    PromptValidationResponse,
    PromptEstimationRequest,
    PromptEstimationResponse,
)
from app.schemas.llm import (
    LLMGenerateRequest,
    LLMGenerateResponse,
    LLMValidationRequest,
    LLMValidationResponse,
    LLMProviderDetails,
    LLMModelListResponse,
    LLMHealthResponse,
)

__all__ = [
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "UserLogin",
    "TokenResponse",
    "RefreshTokenRequest",
    "APIResponse",
    "PaginatedResponse",
    "MetadataFilterModel",
    "RetrieveRequest",
    "RetrieveTopKRequest",
    "RetrieveCourseRequest",
    "RetrieveTopicRequest",
    "RetrieveUnitRequest",
    "ContextChunkRead",
    "ContextPackageRead",
    "PromptTemplateCreate",
    "PromptTemplateUpdate",
    "PromptTemplateRead",
    "PromptBuildRequest",
    "PromptBuildResponse",
    "PromptValidationRequest",
    "PromptValidationResponse",
    "PromptEstimationRequest",
    "PromptEstimationResponse",
    "LLMGenerateRequest",
    "LLMGenerateResponse",
    "LLMValidationRequest",
    "LLMValidationResponse",
    "LLMProviderDetails",
    "LLMModelListResponse",
    "LLMHealthResponse",
    "BloomLevelCreate",
    "BloomLevelRead",
    "KnowledgeLevelCreate",
    "KnowledgeLevelRead",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentRead",
    "ProgramCreate",
    "ProgramUpdate",
    "ProgramRead",
    "SemesterCreate",
    "SemesterUpdate",
    "SemesterRead",
    "CourseOutcomeCreate",
    "CourseOutcomeUpdate",
    "CourseOutcomeRead",
    "CourseCreate",
    "CourseUpdate",
    "CourseRead",
    "UnitCreate",
    "UnitUpdate",
    "UnitRead",
    "TopicCreate",
    "TopicUpdate",
    "TopicRead",
    "TopicMappingCreate",
    "TopicMappingUpdate",
    "TopicMappingRead",
    "ImportReportItem",
    "ResourceRead",
    "ResourceUpdate",
    "DocumentProcessingRead",
    "DocumentMetadataRead",
    "DocumentTextRead",
    "ChunkRead",
    "ChunkMappingRead",
    "ChunkDetailsRead",
    "ChunkPreviewItem",
    "ChunkStatistics",
    "ChunkQualityReportItem",
    "DocumentChunkingJobRead",
]


