"""
Revision History Tracking Service for Learning Materials.
"""

from datetime import datetime
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.learning_material import LearningMaterial


class LearningMaterialHistoryService:
    """
    Manages generation revision tracking, modification history logging, 
    and faculty material audit histories.
    """

    async def log_revision(
        self,
        db: AsyncSession,
        material: LearningMaterial,
        old_content: str,
        changed_by_user_id: str,
        reason: str | None = None,
    ) -> LearningMaterial:
        """
        Append the old state of the learning material to its history metadata list.
        """
        revision_entry = {
            "content": old_content,
            "prompt_version": material.prompt_version,
            "model": material.model,
            "updated_by": str(changed_by_user_id),
            "timestamp": datetime.utcnow().isoformat(),
            "reason": reason or "Regenerated content update",
        }
        
        # history is a mutable list. We copy, append, and reassign to trigger SQLAlchemy state change detection.
        current_history = list(material.history) if material.history else []
        current_history.append(revision_entry)
        material.history = current_history
        material.updated_at = datetime.utcnow()
        await db.flush()
        return material

    async def get_history_by_user(
        self,
        db: AsyncSession,
        user_id: str,
        limit: int = 20,
        offset: int = 0,
    ) -> list[LearningMaterial]:
        """
        Retrieve all materials generated by a specific faculty member.
        """
        stmt = (
            select(LearningMaterial)
            .where(LearningMaterial.created_by == user_id)
            .order_by(LearningMaterial.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        result = await db.execute(stmt)
        return list(result.scalars().all())

    async def get_history_by_course(
        self,
        db: AsyncSession,
        course_id: str,
        limit: int = 20,
        offset: int = 0,
    ) -> list[LearningMaterial]:
        """
        Retrieve all materials generated for a specific course.
        """
        stmt = (
            select(LearningMaterial)
            .where(LearningMaterial.course_id == course_id)
            .order_by(LearningMaterial.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        result = await db.execute(stmt)
        return list(result.scalars().all())
